version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  app:
    image: springboot-app
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    links:
      - mongo