name: Test microservices CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Continuous Integration
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test with Maven
      run: mvn clean install

    - name: Pull containers
      run: docker pull mongo:latest

    - name: Create a new image
      run: docker build . -t "app:latest"

    - name: Run docker compose
      run: docker-compose up -d

    - name: Stop containers
      if: always()
      run: docker-compose down

    # Continuous Development
    - name: Build and Push docker image
      uses: mr-smithers-excellent/docker-build-push@v6

      with:
        image: oiab994/product-service
        tags: v1, latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}