name: Test microservices CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Continuous Integration
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Install with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test


    # Continuous Development
    - name: Build and Push the APP image to Docker Hub
      uses: mr-smithers-excellent/docker-build-push@v6

      with:
        image: oiab994/springboot-app
        tags: v0.2, latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull mongo image
      run: docker pull mongo:latest

    - name: Pull APP image
      run: docker pull oiab994/springboot-app:latest

    - name: Run docker compose
      run: docker-compose up -d

    - name: Stop containers
      if: always()
      run: docker-compose down
